#!/bin/bash

LOG_DIR="/tmp/$(id -un)/log"
NAME=$(basename $1.log)
PATH="$HOME/.local/bin:/home/grzegorz/.local/share/go/bin:$PATH"
killall -q "$1"

mkdir -p /tmp/$(id -un)/log
# Rotate logs if they exist
if test -f "$LOG_DIR/$NAME"; then
	mv "$LOG_DIR/$NAME" "$LOG_DIR/$NAME.old"
fi

$@ 2>&1 | tee -a "$LOG_DIR/$NAME" & disown

echo "Launched \""$@"\""
