#!/bin/bash

FORMAT="%Y-%m-%d_%H-%M-%S.%3N"
SCREENSHOT_DIR="/home/grzegorz/Pictures/screenshots"

SCREENSHOT_PATH=${SCREENSHOT_DIR}/$(date +${FORMAT}).png

$HOME/.local/bin/grimblast --freeze save area $SCREENSHOT_PATH
swappy -f $SCREENSHOT_PATH -o $SCREENSHOT_PATH

wl-copy < $SCREENSHOT_PATH
