#!/bin/bash

swayidle -w \
	lock '$HOME/.config/hypr/scripts/lock -f --grace 0' \
	timeout 840 'xbacklight -dec 20' \
		 resume 'xbacklight -inc 20' \
	timeout 870 '$HOME/.config/hypr/scripts/lock -f --grace 30' \
	before-sleep '$HOME/.config/hypr/scripts/lock -f --grace 0'
