font_family      Maple Mono NF

font_size 12

disable_ligatures never

font_features MapleMono-NF-Regular +ss03 +cv02
font_features MapleMono-NF-SemiBold +ss03 +cv02
font_features MapleMono-NF-Italic +ss03 +cv02 +cv43
