exec-once = runsvdir $HOME/.local/service

exec = sv start polkit
exec = sv start hypridle

exec = sv start wallpaper
exec = sv restart notify
exec = sv restart shell

exec = sv start pipewire
exec = sv start easyeffects

exec = sv start solaar
exec = sv start udiskie

exec = $launch $scripts/batteryd
exec = $launch $scripts/profiled
