#!/bin/bash

TMP_PATH="/tmp/$USER"

mkdir -p $TMP_PATH

if test -f "$TMP_PATH/rgb-mode"; then
	RGB_MODE=$(cat $TMP_PATH/rgb-mode)
else
	RGB_MODE=''
fi

if [[ "$RGB_MODE" == '' || "$RGB_MODE" == 'static' ]]; then
	asusctl led-mode rainbow -d right -s low
	echo "rainbow" > $TMP_PATH/rgb-mode
elif [[ "$RGB_MODE" == 'rainbow' ]]; then
	asusctl led-mode static -c ffffff
	echo "static" > $TMP_PATH/rgb-mode
#elif [[ "$RGB_MODE" == 'static' ]]; then
#	asusctl led-mode static -c ffffff
#	echo "static-kb" > $TMP_PATH/rgb-mode
fi
