#!/bin/bash

FORMAT="%Y-%m-%d_%H-%M-%S.%3N"
SCREENSHOT_DIR="/home/grzegorz/Pictures/screenshots"
SCREENSHOT_NAME=$(date +${FORMAT}).png
SCREENSHOT_PATH=$SCREENSHOT_DIR/$SCREENSHOT_NAME

hyprshot -z -m region -s -f $SCREENSHOT_NAME -o $SCREENSHOT_DIR
swappy -f $SCREENSHOT_PATH -o $SCREENSHOT_PATH

wl-copy < $SCREENSHOT_PATH
