#!/bin/bash

FORMAT="%Y-%m-%d_%H-%M-%S.%3N"
SCREENSHOT_DIR="/home/grzegorz/Pictures/screenshots"
SCREENSHOT_NAME=$(date +${FORMAT}).png
SCREENSHOT_PATH=$SCREENSHOT_DIR/$SCREENSHOT_NAME

hyprshot -m output -m active -s -f $SCREENSHOT_NAME -o $SCREENSHOT_DIR

wl-copy < $SCREENSHOT_PATH
