require('hyprland.env')
require('hyprland.monitors')
require('hyprland.services')
require('hyprland.workspaces')
require('hyprland.input')
require('hyprland.appearance')
require('hyprland.window_rules')
