#!/bin/bash

FORMAT="%Y-%m-%d_%H-%M-%S.%3N"
SCREENSHOT_DIR="/home/grzegorz/Pictures/screenshots"

SCREENSHOT_PATH=${SCREENSHOT_DIR}/$(date +${FORMAT}).png
grim -t png "$SCREENSHOT_PATH"
xclip -selection clipboard -t image/png "$SCREENSHOT_PATH"
